feature_notify_inode_expire_only
libfuse/libfuse pull request #708
Opened 2022-10-27 16:15 UTC by HereThereBeDragons

Related to Issue #707 

This PR extends the unoffical patch provided by Miklos Szeredi  in this [conversation](https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/CAJfpegs8VKu45Jsv%2B-qAWwz2A%2BYpxCtxrFJr%2BA-b1g%2BzKsf%3DOA%40mail.gmail.com/#msg37703271) by 
- hopefully allowing the correct discovery if `fuse_lowlevel_notify_expire_entry` is available or not 
- adding some comments/description

2022-10-29 09:31 UTC, Nikratio requested changes
Thanks! Would it be possible to add a test case for this? (Similar to https://github.com/libfuse/libfuse/blob/master/test/test_ctests.py#L51)

2022-11-09 23:21 UTC, HereThereBeDragons commented
Hi,
So I extended the tests as suggested. However, the current simple file system used for inval_entry will not allow us to correctly test if the functionality is available: right now the test would pass if you have this libfuse patch, but not the kernel patch - it would just work as the "notify_inval_entry" as the new flag is just ignored by the kernel.

Using notify_expire_entry makes only a visible difference for:
- mount on top
- depending on the implementation?: changing symlinks from short to long symlinks

so this needs a bit more sophisticated file system.

if you have any suggestions what would be the easiest to extend, please let me know 
(`passthrough_ll` might be an option but would need to be extended to track dentries)

ps. if you want to have a look: i pushed it to a different [branch](https://github.com/HereThereBeDragons/libfuse/tree/WIP_testing_notify_inode_expire_only) as it doesnt help us here

2022-11-12 09:41 UTC, Nikratio commented
My stance is that a simple test is better than no test. Even if the test passes if the kernel test is missing, it will be able to catch some problems. So let's not make the perfect the enemy of the good.

2022-11-24 16:58 UTC, HereThereBeDragons commented on test/test_examples.py
> +if fuse_proto >= (7,38):
(feel free to remove it - or let me know and i'll do it)

2022-12-14 14:21 UTC, HereThereBeDragons commented
Hi @Nikratio,
Could you please let me briefly know if there is anything else I need to do for this PR in order to be accepted?
Not that I forgetting something from my side.

2022-12-15 21:11 UTC, Nikratio requested changes
Sorry for the delay, I somehow missed that this has been updated.

Thank you for adding the test case. I just have two comments, but generally this looks good.

2022-12-15 21:11 UTC, Nikratio commented on example/notify_expire_entry.c
> + * file name changes dynamically to reflect the current time.
This looks very close to the existing notify_inval_entry.c example. Would it be possible to instead modify the existing example to add a --expire flag (to use the different notification function) to reduce code duplication?

2022-12-15 21:11 UTC, Nikratio commented on test/test_examples.py
> +if fuse_proto >= (7,38):
Well, if it's not needed then let's remove it.

2023-01-02 10:56 UTC, Nikratio commented
Thanks! One last request: could you please combine the last two commits (so that we don't create a new file just to remove it again), and get rid of the remaining whitespace-only changes?

Thank you for your patience, and apologies for the long review time!

2023-01-06 13:10 UTC, HereThereBeDragons commented
Done. Let me know if there is anything else missing.
And np, everything is slow and quiet around Christmas and New Year.

2023-01-06 18:35 UTC, merged