passthrough_hp benchmark mode
libfuse/libfuse pull request #807
Opened 2023-06-27 15:58 UTC by bsbernd

This adds a read/write benchmark mode for passthrough_hp. Minor commits are the forgotten handler for clone_fd and adding in parallel dio writes.

2023-06-29 07:51 UTC, Nikratio commented on example/passthrough_hp.cc
> +         * from a memory buffer
Have you considered splicing the data from /dev/zero instead? That way you could avoid the buffer copy.

2023-06-29 07:56 UTC, Nikratio requested changes
Thanks! Looks good overall, just a few minor comments.

2023-06-29 07:56 UTC, Nikratio commented on example/passthrough_hp.cc
> +        out_buf.buf[0].fd = -1;
Instead of overwriting the previous definiton of out_buf, can we move the first definition into an `else` clause?

2023-06-29 07:56 UTC, Nikratio commented on example/passthrough_hp.cc
> +        fs.bypass_buf = reinterpret_cast<char *>(new uint8_t [1024 * 1024 * 2]);
Can we document why this is the right buffer size, and check for out of bounds writes and reads in the callbacks?

2023-07-05 15:48 UTC, bsbernd commented
Thanks for your comments, I will try to update today or tomorrow

2023-08-08 10:26 UTC, Nikratio commented
@bsbernd Any update on this?

2023-08-08 11:34 UTC, bsbernd commented
Yes sorry, got busy with kernel side again. Let me close for now and I will send out a new version once I'm ready (hopefully during the next days).

2023-08-08 15:23 UTC, Nikratio commented
Let's keep this one open so the comments don't get lost. I've converted it to draft instead.

2026-06-18 06:49 UTC, bsbernd commented
Part of memfs_ll now and not needed in passthrough_hp anymore.

2026-06-18 06:49 UTC, closed without merging